name: build

on:
  workflow_call:
    inputs:
      artifac-filename:
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: ğŸ“š Comprimimos
        run: |
          zip -r ${{inputs.artifac-filename}}.zip .

      - name: â˜ï¸ Subiendo actifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{inputs.artifac-filename}}.zip
          path: ${{inputs.artifac-filename}}.zip