name: tests

on:
  workflow_call:
    inputs:
      artifac-filename:
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: ğŸ“š Empaquetamos
        run: |
          touch ${{inputs.artifac-filename}}
          tar -czf ${{inputs.artifac-filename}} --exclude=${{inputs.artifac-filename}} .

      - name: â˜ï¸ Subiendo actifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{inputs.artifac-filename}}
          path: ${{inputs.artifac-filename}}