name: tests

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  artifact-name:
      runs-on: ubuntu-latest
      outputs:
        artifact-name: ${{ steps.artifact-name.outputs.value }}
      steps:
        - id: artifact-name
          run: echo "::set-output name=value::$(echo ${GITHUB_SHA} | cut -c1-8)"

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{inputs.working-directory}}

    steps:
      - uses: actions/checkout@v2

      - name: ğŸ“‹ Copiar .env.github
        run: yes | cp -rf .env.github .env

      - name: âš™ï¸ Ejecutamos settings
        run: echo ${{inputs.project-name}} |  make settings

      - name: âš™ï¸ Ejecutamos configure
        run: make configure

      - name: âš™ï¸ Ejecutamos permissions
        run: make permissions

      # - name: ğŸ³ Levantamos httpd
      #   run: make build-from-scratch CONTAINER=httpd

      # - name: ğŸ³ Levantamos php
      #   run: make build-from-scratch CONTAINER=php

      # - name: ğŸ³ Levantamos mysql
      #   run: make build-from-scratch CONTAINER=mysql

      # - name: ğŸ» Instalamos dependencias
      #   run: |
      #     export COMPOSE_INTERACTIVE_NO_CLI=1
      #     make composer

      # - name: âœ… Lanzamos tests
      #   run: make unit-test